name: mc-ledger-test

env:
  SGX_MODE: SW
  IAS_MODE: DEV
  RUST_BACKTRACE: full
  CONSENSUS_ENCLAVE_CSS: /var/tmp/consensus-enclave.css
  INGEST_ENCLAVE_CSS: /var/tmp/ingest-enclave.css

on:
  push:
    branches:
      - setup-mobilecoin
  pull_request:
    branches:
      - main
      - setup-mobilecoin

jobs:
  explore-space:
    runs-on: [self-hosted, Linux, large]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  setup-ledger:
    runs-on: [self-hosted, Linux, large]
    steps:
      - name: Check out MobileCoin repo
        uses: actions/checkout@v3
        with:
          repository: mobilecoinfoundation/mobilecoin
          ref: master
    
      - name: Check out Full Service repo
        uses: actions/checkout@v3
        with:
          repository: mobilecoinfoundation/full-service
          submodules: recursive
          ref: main
      
      - name: ls workspace
        run: |
          echo "$(ls ${{ github.workspace }})"
        
      # - name: Run Mobilecoin ledger deployment script
      #   run: ./.github/scripts/start_mobilecoin_ledger.sh
      #   shell: bash