name: mc-ledget-test

env:
  SGX_MODE: SW
  IAS_MODE: DEV
  RUST_BACKTRACE: full
  CONSENSUS_ENCLAVE_CSS: /var/tmp/consensus-enclave.css
  INGEST_ENCLAVE_CSS: /var/tmp/ingest-enclave.css
  MC_SEED: a4aa76e4a5ca70c8447dd544a63f180b5a6fe0aff96495802506354c10f2886e
  LEDGER_BASE: /tmp/mobilenode/target/sample_data/ledger
  IAS_API_KEY: ${{ secrets.SGX_PRIMARY_API_KEY }}
  IAS_SPID: ${{ secrets.SGX_SPID }}

on:
  push:
    branches:
      - brian/setup-mobilecoin

jobs:
  test:
    runs-on: [self-hosted, Linux, large]
    container:
      image: mobilecoin/rust-sgx-base:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Brew Bundle
        run: |
          brew update --preinstall
          brew bundle --no-upgrade
      
      - name: Git Submodule
        run: |
          git submodule update --checkout --init --recursive

      - name: Cache Cargo
        if: steps.artifact_cache.outputs.cache-hit != 'true'
        id: cargo_cache
        uses: actions/cache@v3
        with:
          path: |
            /opt/cargo/bin/
            /opt/cargo/registry/index/
            /opt/cargo/registry/cache/
            /opt/cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Bootstrap MobileCoin
        run: |
          mobilecoin/tools/local-network/bootstrap.sh
      
      - name: Run MobileCoin
        shell: bash
        run: |
          python3 mobilecoin/tools/local-network/local_network.py --network-type a-b-c