name: mc-ledger-test

env:
  SGX_MODE: SW
  IAS_MODE: DEV
  RUST_BACKTRACE: full
  CONSENSUS_ENCLAVE_CSS: /var/tmp/consensus-enclave.css
  INGEST_ENCLAVE_CSS: /var/tmp/ingest-enclave.css

on:
  push:
    branches:
      - setup-mobilecoin
  pull_request:
    branches:
      - main
      - setup-mobilecoin

jobs:
  setup-ledger:
    runs-on: [self-hosted, Linux, large]
    steps:
      - name: Check out MobileCoin repo
        uses: actions/checkout@v3
        with:
          repository: mobilecoinfoundation/mobilecoin
          ref: master
          path: mobilecoin
    
      - name: Check out Full Service repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: main
          path: full-service

      - name: Start MobileCoin Ledger
        shell: 'script -q -e -c "bash {0}"'
        run: >
          cd ./mobilecoin
          && echo "Starting Docker container..."
          && docker run -t -i
          --env CARGO_HOME=/tmp/mobilenode/cargo
          --volume ${{ github.workspace }}/mobilecoin:/tmp/mobilenode
          --workdir /tmp/mobilenode
          --expose 8080
          --expose 8081
          --expose 8443
          --expose 3223
          --expose 3225
          --expose 3226
          --expose 3228
          --expose 4444
          --expose 3200
          --expose 3201
          --expose 3202
          --publish 3200:3200
          --publish 3201:3201
          --publish 3202:3202
          --cap-add SYS_PTRACE
          --name mobilecoin
          ubuntu /bin/bash -c
          'echo "Installing rust..."
          && apt-get update
          && apt-get install --yes curl build-essential protobuf-compiler cmake software-properties-common llvm llvm-dev
          python3.9 pkg-config libssl-dev clang libclang-dev libc-dev libsqlite3-dev libprotobuf-dev
          && wget https://download.01.org/intel-sgx/sgx-linux/2.9.1/distro/ubuntu18.04-server/sgx_linux_x64_sdk_2.9.101.2.bin
          && chmod +x sgx_linux_x64_sdk_2.9.101.2.bin
          && sudo ./sgx_linux_x64_sdk_2.9.101.2.bin --prefix=/opt/intel
          && curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
          && source /tmp/mobilenode/cargo/env
          && echo "$(command -v cargo)"
          && rustup toolchain install nightly --allow-downgrade --profile minimal --component clippy
          && rustc --version
          && protoc --version
          && echo "Running mobilecoin/tools/local-network/bootstrap.sh..."
          && cd tools/local-network
          && echo "Setting up environment variables..."
          && export MC_SEED=a4aa76e4a5ca70c8447dd544a63f180b5a6fe0aff96495802506354c10f2886e
          && export LEDGER_BASE=/tmp/mobilenode/target/sample_data/ledger
          && export IAS_API_KEY=${{ secrets.SGX_PRIMARY_API_KEY }}
          && export IAS_SPID=${{ secrets.SGX_SPID }}
          && export SGX_MODE=HW
          && export IAS_MODE=PROD
          && ./bootstrap.sh
          && echo "running mobilecoin/tools/local-network/local_network.py..."
          && python3 local_network.py --network-type a-b-c'